services:
  db:
    image: mysql:8.0
    container_name: dodo-mysql
    ports:
      - "${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - dodo-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7.0-alpine
    container_name: dodo-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - dodo-network
  app:
    image: gnsehs/dodo-server:latest
    container_name: dodo-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    networks:
        - dodo-network

networks:
  dodo-network:
    driver: bridge
