spring:
  application:
    name: dodo-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 기본값(:default)을 설정하여 로딩 실패 방지
    url: jdbc:mysql://localhost:${DB_LOCAL_PORT:3306}/${DB_NAME:dodo_db}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:dodo_user}
    password: ${DB_PASSWORD:dodo_password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Dialect를 명시하여 Hibernate가 DB 종류를 바로 알 수 있게 함
        dialect: org.hibernate.dialect.MySQLDialect
